from typing import Any

class DiscreteActionSpace:
    open_ai_gym_space: Any = ...
    action_space_size: Any = ...
    def __init__(self, action_space_size: int) -> None: ...
    def __iter__(self) -> DiscreteActionSpace: ...
    def __next__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def sample(self) -> int: ...
    def get_open_ai_gym_action_space(self) -> None: ...
