from smartish.actions.discrete_action_space import DiscreteActionSpace as DiscreteActionSpace
from typing import Any, List, Optional

class SocialPreferenceConversionError(RuntimeError):
    def __init__(self, num_agents: int, action: Optional[int]=..., actions: Optional[int]=..., agent_id: Optional[int]=...) -> None: ...

class SocialPreferenceActionSpace(DiscreteActionSpace):
    num_agents: Any = ...
    def __init__(self, num_agents: int) -> None: ...
    def convert_to_social_preference_list(self, agent_id: int, action: int) -> List[bool]: ...
    def convert_to_social_preference_matrix(self, actions: List[int]) -> List[List[bool]]: ...
